version: "3"
services:
    web:
        build: ./mssql-aspcore-example-app
        environment: 
            db-hostname: "db"
        ports:
            - "5000:5000"
        depends_on:
            - db
    db:
        build: ./mssql-aspcore-example-db
        environment:
            SA_PASSWORD: "Yukon900"
            ACCEPT_EULA: "Y"
        ports:
            - "1500:1433"